### ISSUE TITLE
Adding options to configure the output

### ISSUE THREAD

**Issue by Pantastisch** [bblanchon/ArduinoTrace#3]
Adding options to configure the output would be a nice feature.

For example in most cases you don't need the filename, because it is mostly the "main" *.ino file

**Comment by bblanchon** [comment]
ArduinoTrace 1.1.0 only prints the file name by default (instead of the full path).
Maybe that's enough?

I'm not sure entirely removing the filename is useful.
What do you think?

**Comment by Pantastisch** [comment]
I tested 1.1.0 and printing the file name instead of the full path is definitely a better result.

Removing the file name was only one of several examples for configuration the output.

Other examples to configure could be showing the datatypes, showing the line or print the hole path instead of only the file name with true/false decisions.

**Comment by Pantastisch** [comment]
I just saw, print the hole path instead of only the file name is already done as configuration 👍

**Comment by bblanchon** [comment]
The problem with a request like "Adding options to configure the output" is that it's too vague; it's a request that will never be fulfilled because there will always be someone who wants one more option.

That's why I prefer closing this issue.
I invite you to open new ones with specific needs (like "remove line number" or "add variable type") when you need them.

Thank you for your understanding.
